name: Build MLIR

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-18.04, windows-latest, macos-latest]
        os: [ubuntu-18.04]

    env:
      # build using a different image from the docker registry
      CIBW_MANYLINUX_X86_64_IMAGE: dockcross/manylinux-x64
      CIBW_MANYLINUX_I686_IMAGE: dockcross/manylinux-x86

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.2

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
